### ISSUE TITLE
Adding track maintainers

### ISSUE THREAD

**Issue by rlmark** [exercism/unison#32]
Hello! Apologies if this is the wrong place to file the request to add track maintainers! I'm hoping to add a few folks from the Unison team as track maintainers so that they can maintain and QA the track. 

Their github usernames are: 
- [x] [`pchiusano`](https://github.com/pchiusano)
- [x] [`runarorama`](https://github.com/runarorama)
- [x] [`hojberg`](https://github.com/hojberg) 
- [x] [`stew` ](https://github.com/stew)
- [x] [`aryairani`](https://github.com/aryairani)

We may have a few straggler maintainer requests come through, but those are the folks who initially responded!

**Comment by ErikSchierboom** [comment]
@iHiD Could you add them to the `unison` team?

**Comment by ErikSchierboom** [comment]
@rlmark I can't find a user with their github username equal to `pchuisano` in our database. Could you ask them to login via github on our website?

**Comment by ErikSchierboom** [comment]
I've made the other three account maintainers on the website, so they can see and interact with the Unison track.

**Comment by rlmark** [comment]
Apologies! That's [pchiusano](https://github.com/pchiusano) I flipped the `u` and `i`. 

And we had another person make a request from the team! I've updated the list and turned it into a check box format for easier tracking.

**Comment by ErikSchierboom** [comment]
All done. @iHiD will add them to the unison github team.
